const ALL_EVENT_KEYS = {
    "Canadian Rockies Regional": "2020abca",
    "Rocket City Regional": "2020alhu",
    "Arkansas Regional": "2020arli",
    "Southern Cross Regional": "2020ausc",
    "South Pacific Regional": "2020ausp",
    "Arizona North Regional": "2020azfl",
    "Arizona West Regional": "2020azpx",
    "Canadian Pacific Regional": "2020bcvi",
    "***POSTPONED*** Beijing Cultural Exchange Event #1": "2020bexi",
    "***POSTPONED*** Beijing Cultural Exchange Event #2": "2020bexi2",
    "Aerospace Valley Regional": "2020caav",
    "Sacramento Regional": "2020cada",
    "Del Mar Regional": "2020cadm",
    "Central Valley Regional": "2020cafr",
    "Los Angeles Regional": "2020cala",
    "Los Angeles North Regional": "2020caln",
    "Monterey Bay Regional": "2020camb",
    "Orange County Regional": "2020caoc",
    "San Diego Regional presented by Qualcomm": "2020casd",
    "San Francisco Regional": "2020casf",
    "Silicon Valley Regional": "2020casj",
    "SCRRF SoCal Spring Scrimmage": "2020cass",
    "Ventura Regional": "2020cave",
    "FIRST Chesapeake District Championship sponsored by Newport News Shipbuilding": "2020chcmp",
    "Science Park Taichung Regional": "2020chta",
    "FIRST Championship (Detroit)": "2020cmpmi",
    "FIRST Championship (Houston)": "2020cmptx",
    "Colorado Regional": "2020code",
    "NE District Hartford Event": "2020cthar",
    "NE District Northern CT Event": "2020ctnct",
    "NE District Waterbury Event": "2020ctwat",
    "FACC Ri3D Competition": "2020facc",
    "Orlando Regional": "2020flor",
    "South Florida Regional": "2020flwp",
    "FIRST In Texas District Championship": "2020ftcmp",
    "PCH District Albany Event presented by Procter & Gamble": "2020gaalb",
    "PCH District Carrollton Event": "2020gacar",
    "Peachtree District State Championship": "2020gacmp",
    "PCH District Columbus Event": "2020gacol",
    "PCH District Dalton Event": "2020gadal",
    "PCH District Gainesville Event presented by Automation Direct": "2020gagai",
    "Hawaii Regional": "2020hiho",
    "Iowa Regional": "2020iacf",
    "Idaho Regional": "2020idbo",
    "Midwest Regional": "2020ilch",
    "Central Illinois Regional": "2020ilpe",
    "IN District Bloomington Event": "2020inblo",
    "Indiana State Championship": "2020incmp",
    "IN District Columbus Event": "2020incol",
    "IN District St. Joseph Event": "2020inmis",
    "IN District Perry Meridian Event": "2020inpmh",
    "FIRST Israel District Championship": "2020iscmp",
    "ISR District Event #1": "2020isde1",
    "ISR District Event #2": "2020isde2",
    "ISR District Event #3": "2020isde3",
    "ISR District Event #4": "2020isde4",
    "Heartland Regional": "2020ksla",
    "Bayou Regional": "2020lake",
    "NE District Greater Boston Event": "2020mabos",
    "NE District SE Mass Event": "2020mabri",
    "NE District North Shore Event": "2020marea",
    "NE District Western NE Event": "2020mawne",
    "NE District WPI Event": "2020mawor",
    "CHS District Bethesda MD Event": "2020mdbet",
    "CHS District Edgewater MD Event sponsored by Leidos": "2020mdedg",
    "CHS District Owings Mills MD Event": "2020mdowi",
    "NE District Pine Tree Event": "2020melew",
    "FIM District Alpena Event #2": "2020mial2",
    "FIM District Alpena Event #1": "2020mialp",
    "FIM District Belleville Event": "2020mibel",
    "FIM District Center Line Event": "2020micen",
    "Michigan State Championship": "2020micmp",
    "FIM District Detroit Event": "2020midet",
    "FIM District Escanaba Event": "2020miesc",
    "FIM District Ferris State Event": "2020mifer",
    "FIM District Gull Lake Event": "2020migul",
    "FIM District Jackson Event": "2020mijac",
    "FIM District Kettering University Event #2": "2020mike2",
    "FIM District East Kentwood Event": "2020miken",
    "FIM District Kettering University Event #1": "2020miket",
    "FIM District Kingsford Event": "2020mikng",
    "FIM District Lakeview Event": "2020milak",
    "FIM District Lansing Event": "2020milan",
    "FIM District Lincoln Event": "2020milin",
    "FIM District Livonia Event": "2020miliv",
    "FIM District Marysville Event": "2020mimar",
    "FIM District Macomb Community College Event": "2020mimcc",
    "FIM District Midland Event": "2020mimid",
    "FIM District Milford Event": "2020mimil",
    "FIM District Muskegon Event": "2020mimus",
    "FIM District Shepherd Event": "2020mishe",
    "FIM District St. Joseph Event": "2020misjo",
    "FIM District Southfield Event": "2020misou",
    "FIM District Troy Event": "2020mitry",
    "FIM District Traverse City Event": "2020mitvc",
    "FIM District West Michigan Event": "2020miwmi",
    "FIM District Woodhaven Event": "2020miwoo",
    "Lake Superior Regional": "2020mndu",
    "Northern Lights Regional": "2020mndu2",
    "Minnesota 10,000 Lakes Regional Presented by the Medtronic Foundation": "2020mnmi",
    "Minnesota North Star Regional": "2020mnmi2",
    "West Central Week 0": "2020mnwcw",
    "Greater Kansas City Regional": "2020mokc",
    "Central Missouri Regional": "2020mokc3",
    "St. Louis Regional": "2020mosl",
    "FIRST Mid-Atlantic District Championship": "2020mrcmp",
    "Regional Monterrey": "2020mxmo",
    "Regional Laguna": "2020mxto",
    "FNC District UNC Asheville Event": "2020ncash",
    "FIRST North Carolina State Championship": "2020nccmp",
    "FNC District ECU Event": "2020ncgre",
    "FNC District Guilford County Event": "2020ncgui",
    "FNC District UNC Pembroke Event": "2020ncpem",
    "FNC District Wake County Event": "2020ncwak",
    "Great Northern Regional": "2020ndgf",
    "New England District Championship": "2020necmp",
    "NE District Granite State Event": "2020nhgrs",
    "NE District Southern NH Event": "2020nhsnh",
    "FMA District Bridgewater-Raritan Event": "2020njbri",
    "FMA District Mount Olive Event": "2020njfla",
    "FMA District Robbinsville Event": "2020njrob",
    "FMA District Montgomery Event": "2020njski",
    "FMA District Seneca Event": "2020njtab",
    "Las Vegas Regional": "2020nvlv",
    "SBPLI Long Island Regional #1": "2020nyli",
    "SBPLI Long Island Regional #2": "2020nyli2",
    "New York City Regional": "2020nyny",
    "Finger Lakes Regional": "2020nyro",
    "Rochester Rally": "2020nyrra",
    "Hudson Valley Regional": "2020nysu",
    "New York Tech Valley Regional": "2020nytr",
    "Central New York Regional": "2020nyut",
    "Buckeye Regional": "2020ohcl",
    "Miami Valley Regional": "2020ohmv",
    "Oklahoma Regional": "2020okok",
    "Green Country Regional": "2020oktu",
    "ONT District Georgian College Event": "2020onbar",
    "FIRST Ontario Provincial Championship": "2020oncmp",
    "ONT District McMaster University Event": "2020onham",
    "ONT District Western University, Western Engineering Event": "2020onlon",
    "ONT District North Bay Event": "2020onnob",
    "ONT District York University Event": "2020onnyo",
    "ONT District Durham College Event": "2020onosh",
    "ONT District Carleton University Event": "2020onott",
    "ONT District Ryerson University Event": "2020onto1",
    "ONT District Humber College Event": "2020onto3",
    "ONT District University of Waterloo Event": "2020onwat",
    "ONT District Windsor Essex Great Lakes Event": "2020onwin",
    "PNW District Clackamas Academy Event": "2020orore",
    "PNW District Oregon State Fairgrounds Event": "2020orsal",
    "PNW District Wilsonville Event": "2020orwil",
    "FMA District Bensalem Event": "2020paben",
    "Greater Pittsburgh Regional": "2020paca",
    "FMA District Hatboro-Horsham Event": "2020pahat",
    "FMA District Springside Chestnut Hill Academy Event": "2020paphi",
    "Pacific Northwest FIRST District Championship": "2020pncmp",
    "Festival de Robotique a Montreal Regional": "2020qcmo",
    "Festival de Robotique a Sherbrooke Regional": "2020qcsh",
    "Palmetto Regional": "2020scmb",
    "Seven Rivers Robotics Coalition Week Zero": "2020srrc",
    "Smoky Mountains Regional": "2020tnkn",
    "Memphis Regional": "2020tnme",
    "Istanbul Regional": "2020tuis",
    "Bosphorus Regional": "2020tuis2",
    "FIT District Amarillo Event": "2020txama",
    "FIT District Austin Event": "2020txaus",
    "FIT District Channelview Event": "2020txcha",
    "FIT District Del Rio Event": "2020txdel",
    "FIT District Dallas Event": "2020txdls",
    "FIT District Dripping Springs Event": "2020txdri",
    "FIT District El Paso Event": "2020txelp",
    "FIT District Fort Worth Event": "2020txfor",
    "FIT District Greenville Event": "2020txgre",
    "FIT District Houston Event": "2020txhou",
    "FIT District New Braunfels Event": "2020txnew",
    "FIT District Pasadena Event": "2020txpas",
    "FIT District Plano Event": "2020txpla",
    "Utah Regional": "2020utwv",
    "CHS District Blacksburg VA Event": "2020vabla",
    "CHS District Richmond VA Event": "2020vagle",
    "CHS District Haymarket VA Event": "2020vahay",
    "CHS District Portsmouth VA Event": "2020vapor",
    "PNW District Auburn Event": "2020waahs",
    "PNW District Auburn Mountainview Event": "2020waamv",
    "PNW District Bellingham Event": "2020wabel",
    "PNW District Glacier Peak Event": "2020wasno",
    "PNW District West Valley Event": "2020waspo",
    "PNW District SunDome Event": "2020wayak",
    "Week 0": "2020week0",
    "Seven Rivers Regional": "2020wila",
    "Wisconsin Regional": "2020wimi",
    "Sussex Mini-Regional": "2020wiss"
};

function get_all_event_names() {
    return Object.keys(ALL_EVENT_KEYS);
}

function get_event_key_from_name(name) {
    return ALL_EVENT_KEYS[name];
}

function search_for_events(query) {
    return get_all_event_names().filter(name => name.toLowerCase().indexOf(query.toLowerCase()) > 0);
}

function get_event_name_from_key(key) {
    get_all_event_names.forEach(n => {
        if (ALL_EVENT_KEYS[n] == key) return n;
    });
    throw new Error("ERROR: key '" + key + "' does not exist");
}